---
title: Ideaonce
timezone: America/Mexico_City
collections:
  clients:
    title: Clients
    output: false
  posts:
    title: Posts
    output: true
  solutions:
    title: Solutions
    output: false
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: 'Creamos soluciones adaptadas a tus necesidades

'
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
